"""
French translations of WC4 elite unit feature names & descriptions.
Keys are the integer Type value from ArmyFeatureSettings.Type.
Descriptions keep {0}/{1}/{2}/{3}/{4}/{5} placeholders filled at runtime.
"""

FEATURE_FR = {
    1:   ("Sapeur",                          "Dégâts subis des mines terrestres -{1}%"),
    2:   ("Grenade",                         "Dégâts aux unités blindées +{1}%"),
    4:   ("Marche forcée",                   "Consommation de mobilité sur terrain difficile -{1}%"),
    5:   ("Anti-char",                       "Dégâts aux unités blindées +{1}%"),
    6:   ("Samouraï",                        "Volonté du guerrier : l'efficacité au combat ne baisse pas quand les PV diminuent"),
    7:   ("Milice",                          "Ravitaillement +{1}% dans la ville"),
    8:   ("Commando de montagne",            "Dégâts à l'ennemi +{1}% en combat en montagne"),
    10:  ("Commando de forêt",               "Dégâts à l'ennemi +{1}% en combat en jungle"),
    11:  ("Tireur d'élite",                  "Dégâts aux unités d'infanterie +{1}%"),
    12:  ("Mitrailleuse",                    "Dégâts aux unités d'infanterie +{1}%"),
    13:  ("Assaut",                          "{0}% de chances d'attaquer à nouveau après avoir détruit un ennemi"),
    14:  ("Défense aérienne",                "Système anti-aérien équipé sur les forces blindées"),
    15:  ("Puissance de feu",                "{0}% de chances d'empêcher l'ennemi de riposter"),
    16:  ("Roquettes",                       "Frappe plusieurs ennemis à la fois et {0}% de chances de les empêcher de riposter"),
    17:  ("Torpille",                        "Dégâts +{1}% contre les croiseurs et porte-avions"),
    18:  ("Artillerie navale",               "Dégâts aux fortifications +{1}% et aux unités terrestres -50%"),
    19:  ("Dragueur de mines",               "Dégâts subis des mines navales -{1}%"),
    20:  ("Défense aérienne",                "Système anti-aérien équipé sur les navires de guerre"),
    21:  ("Immersion",                       "L'ennemi ne peut pas riposter lors de l'attaque ; immunité aux unités terrestres hormis l'artillerie côtière"),
    22:  ("Frappe aérienne",                 "Dégâts des mitrailleuses lourdes de chasseur aux unités d'infanterie +{1}%"),
    23:  ("Bombardement",                    "Dégâts des bombardiers aux unités navales +{1}%"),
    25:  ("Bombardement stratégique",        "Dégâts de bombardement massif aux fortifications +{1}%"),
    35:  ("Porte-avions",                    "Peut attaquer via ses aéronefs embarqués"),
    39:  ("Grenade sous-marine",             "Dégâts aux sous-marins +{1}%"),
    43:  ("Marche rapide",                   "Peut agir à nouveau après une action — récupération en 1 tour"),
    44:  ("Attaque critique",                "Probabilité de coup critique +{1}%"),
    45:  ("Dégâts critiques",                "Dégâts des coups critiques +{1}%"),
    46:  ("Tir de précision",                "Probabilité de coup critique +{1}% pendant 1 tour — récupération en 2 tours"),
    47:  ("Secours d'urgence",               "Restaure {1} PV à un allié ciblé — récupération en 1 tour"),
    49:  ("Perforation",                     "Dégâts aux cibles terrestres à PV maximum +{1}%"),
    50:  ("Salve",                           "Frappe plusieurs ennemis à la fois sans réduction de dégâts sur les cibles secondaires"),
    51:  ("Artillerie géante",               "Portée +2, dégâts majorés : -{1}% PV de la ville/forteresse ciblée (max 1200), -{2}% PV de la garnison (max 500). Récupération en 3 tours."),
    52:  ("Blindage incliné",                "{0}% de chances de réduire les dégâts reçus de {1}% pendant 1 tour. Récupération en 2 tours."),
    53:  ("Chasseur de chars",               "Dégâts aux unités blindées et d'artillerie +{1}% pendant 1 tour. Récupération en 2 tours."),
    54:  ("Tueur d'artillerie",              "Dégâts aux unités d'artillerie +{1}% pendant 1 tour. Récupération en 2 tours."),
    55:  ("Préparation aérienne",            "Coût de construction des unités aériennes -{1}%"),
    56:  ("Piqué hurlant",                   "{0}% de chances de baisser le moral de l'ennemi et la même chance d'embraser la case"),
    57:  ("Transport aérien",                "Transporte une unité d'infanterie, un véhicule blindé, une artillerie de campagne ou un obusier vers une case cible"),
    58:  ("Tactique de la meute",            "Dégâts +{1}% en attaquant des navires de transport"),
    59:  ("Artillerie navale lourde",        "Dégâts aux forteresses +{1}% et aux unités terrestres +{2}%"),
    60:  ("Pose de mines",                   "Dépose des mines navales de contact dans un rayon d'1 case — récupération en 1 tour"),
    61:  ("Tir de suppression",              "La prochaine attaque touche 1 ennemi supplémentaire adjacent (dégâts secondaires -50%). Récupération en 2 tours."),
    62:  ("Entrave",                         "Immobilise les ennemis dans un rayon d'1 case pendant 1 tour. Récupération 3 tours — ramenée à 1 tour si 3 cibles ou plus."),
    63:  ("Assaut",                          "Dégâts à la défense de ville +{1}% pendant 2 tours. Récupération en 3 tours."),
    64:  ("Frappe au dépourvu",              "Le taux de critique excédentaire devient dégâts bonus : pour chaque {2}% de critique en excès, +{1}% de dégâts"),
    65:  ("Canon à grande vitesse",          "Ignore {1}% de la défense ennemie"),
    66:  ("Tueur de chars",                  "Dégâts aux unités blindées +{1}% ce tour. Récupération en 2 tours."),
    67:  ("Blindage en coin",                "Dégâts de riposte +{1}%"),
    68:  ("Poursuite",                       "Après une attaque, si l'adversaire est anéanti, {0}% de chances d'agir à nouveau — maximum {2} fois"),
    69:  ("Frappe coordonnée",               "Quand un allié dans 1 case attaque, {0}% de chances de participer à l'attaque"),
    70:  ("Raid aérien intensif",            "En attaquant, inflige {1}% de dégâts supplémentaires aux cibles dans 1 case autour. Récupération en 2 tours."),
    71:  ("Regroupement",                    "Peut effectuer {1} attaque(s) supplémentaire(s)"),
    72:  ("Port aérien maritime",            "Peut utiliser tous les aéronefs classiques de l'aéroport, maximum {1} points d'aéronefs"),
    73:  ("Obus explosif",                   "Dégâts normaux contre les chars +{1}%"),
    74:  ("Neutralisation des défenses",     "{1}% de chances de détruire les défenses anti-aériennes de la ville"),
    75:  ("Attaque des Flying Tigers",       "Booste le moral d'un allié aléatoire dans 1 case autour de la cible attaquée"),
    76:  ("Attaque à la roquette",           "Portée ramenée à 2, frappe plusieurs ennemis, {1}% de chances que les ennemis ne puissent pas riposter pendant 1 tour. Récupération en 2 tours."),
    77:  ("Gilet pare-éclats",               "Dégâts subis des unités blindées -{1}%"),
    78:  ("Visée infrarouge",                "Ignore l'esquive et les fumigènes, et inflige +{1}% de dégâts aux défenses de ville"),
    79:  ("Fumigène",                        "Se cache derrière un écran de fumée ; ne peut être ciblé activement par les unités terrestres pendant 1 tour. Récupération en 3 tours."),
    80:  ("Obus HEAT",                       "Sous effet de fumigène, ignore {1}% de la défense ennemie"),
    81:  ("Dissuasion nucléaire stratégique", "Les missiles peuvent charger des ogives atomiques : 2 initialement, +1 toutes les {1} tour(s), maximum 4"),
    82:  ("Attaque au missile",              "Peut tirer des missiles balistiques à courte portée jusqu'à 2 fois par tour — remplace l'attaque normale"),
    83:  ("Navigation en eaux profondes",    "Ne peut pas être ciblé par les unités terrestres ; dégâts subis des unités aériennes -{1}%"),
    84:  ("Mitraillage",                     "Trace une ligne droite jusqu'à {1} cases (case d'arrivée dégagée, bloquée par les unités en vol), infligeant des dégâts de mitraillage sur le trajet. Récupération en 2 tours."),
    85:  ("Supériorité aérienne",            "Peut décoller à 1 case d'un porte-avions. Ignore tous les effets de terrain sur la mobilité et toutes les mines. L'ennemi ne peut pas riposter. L'efficacité au combat ne baisse pas quand les PV diminuent."),
    87:  ("Manœuvres d'évasion",             "{1}% de chances d'esquiver les dégâts infligés par les unités terrestres ou navales"),
    88:  ("Pose de mines terrestres",        "Dépose une mine dans 1 case — {1} points de dégâts. Récupération en 1 tour."),
    89:  ("Creusement de tunnel",            "Creuse un tunnel jusqu'à 4 cases (hors montagne et océan) : infanterie, chars légers/moyens, roquettes, véhicules blindés, artillerie de campagne et obusiers peuvent y passer. Actions bonus après passage, maximum 3 fois par tunnel. Un nouveau tunnel efface le précédent. Récupération en 2 tours."),
    90:  ("Maintenance",                     "Les bâtiments dans 1 case autour récupèrent {1} point de PV une fois par tour"),
    92:  ("Frappe vengeresse",               "Attaque +{2} pour chaque {1} points de PV perdus"),
    93:  ("Dispositif de protection",        "L'efficacité au combat ne baisse pas quand les PV diminuent. Seuil de survie : les PV ne peuvent descendre sous 1 point pendant 2 tours. Récupération en {2} tours."),
    94:  ("Avantage local",                  "Sur votre territoire ou celui d'un allié, dégâts infligés +{1}%"),
    95:  ("Passe-partout",                   "Ignore les réductions de dégâts liées au terrain en attaque comme en riposte"),
    96:  ("Combat côte à côte",              "Les dégâts directs sont partagés avec les alliés adjacents ; pour chaque {1} point de dégât partagé ou esquivé, +{2} d'attaque de base (plafond +100%). Durée 2 tours."),
    97:  ("Esquive rapide",                  "{1}% de chances d'esquiver les dégâts des frappes aériennes"),
    98:  ("Fantôme",                         "Passe en état fantôme, ne peut être ciblé activement par les unités terrestres ou navales. Mobilité +{1} pendant 1 tour. L'état fantôme prend fin à l'attaque. Récupération en 2 tours."),
    99:  ("Assassinat",                      "Ne peut pas être ripostée. Dégâts aux ennemis +{1}% (et +{2}% en état fantôme). Dégâts aux bâtiments -50%."),
    100: ("Saut aérien",                     "Appelle des hélicoptères pour se téléporter jusqu'à 5 cases. Récupération en 2 tours."),
    101: ("Pansement d'urgence",             "Récupère {1}% des PV max au tour suivant si les PV sont à moins de la moitié"),
    102: ("Munition à uranium appauvri",     "Probabilité de critique +{1}% et ignore {2}% de la défense de la cible ce tour. Récupération en 2 tours."),
    103: ("Blindage à uranium appauvri",    "Défense +{1}%"),
    104: ("Bombardement à haute altitude",   "Les armes anti-aériennes ne peuvent pas intercepter le bombardement à haute altitude"),
    105: ("Charge excessive",                "Ne peut pas servir d'aéronef embarqué. Chaque attaque inflige +{1}% de dégâts dans la zone ciblée"),
    106: ("Frappe atomique",                 "En attaquant avec une bombe nucléaire, les dégâts nucléaires sont augmentés de {1}%"),
    107: ("Feu d'enfer",                     "Inflige +{1}% de dégâts aux cibles dans 1 case autour de la cible principale ce tour. Récupération en 2 tours."),
    108: ("Assaut à basse altitude",         "Peut frapper plusieurs ennemis — dégâts aux chars et à l'artillerie +{1}%"),
    109: ("Impulsion électromagnétique",     "Annule la plupart des buffs des ennemis dans 1 case autour. Récupération en 3 tours."),
    110: ("Camouflage",                      "En terrain de montagne ou de forêt, dégâts subis -{1}%"),
    111: ("Attaque saturante",               "Tire plusieurs missiles balistiques courte portée : {1}% des dégâts à la cible et {2}% aux ennemis adjacents. Récupération en 3 tours."),
    116: ("Guidage céleste",                 "Dans un rayon de 3 cases, choisit {1} cible(s) et lance des missiles : inflige des dégâts et -{2}% de défense pendant 2 tours. Récupération en 3 tours."),
    117: ("Frappe dévastatrice",             "Si les PV de la cible sont supérieurs ou égaux à {1}%, cette attaque est un critique garanti"),
    121: ("Incitation au courage",           "En prenant une ville ennemie, booste le moral des alliés dans 3 cases autour pendant 2 tours"),
    122: ("Soutien logistique",              "Les alliés dans 2 cases récupèrent {1} PV après avoir subi des dégâts directs"),
    123: ("Protection critique",             "Pour chaque {1}% de PV perdus, dégâts reçus -{2}% (plafond 25%). Dégâts reçus plafonnés à 300 (hors bombes nucléaires)."),
    124: ("Partage de dégâts",               "Propage {1}% des dégâts directs reçus aux ennemis dans 1 case"),
    125: ("Protection tactique",             "Défense +{1}% aux alliés dans 2 cases autour"),
    126: ("Déviation balistique",            "En subissant des dégâts d'une unité terrestre, {0}% de chances de transférer ces dégâts à une cible dans 1 case (hors unité attaquante)"),
    127: ("Brise-fer",                       "Pour chaque {1} point de défense de la cible, dégâts infligés +{2}%"),
    128: ("Suppression continue",            "Applique un effet réduisant les PV de la cible de 10% par tour pendant 2 tours"),
    129: ("Renforcement de feu",             "Attaque +{1}% pour chaque unité détruite — cumulable jusqu'à {2} fois, durée 2 tours"),
    130: ("Interférence visuelle",           "Sous fumigène, la portée des ennemis dans 2 cases est ramenée à {1} (annulé si l'effet fumigène est ignoré)"),
    131: ("Déploiement rapide",              "Sur votre territoire ou celui d'un allié, mobilité +{1}"),
    132: ("Assaut aéroporté",                "+{1}% de dégâts infligés le tour suivant un saut aéroporté"),
    133: ("Construction de voies",           "Si aucune action n'est effectuée durant un tour, mobilité du tour suivant +{1}"),
    134: ("Châssis léger",                   "Peut être aérotransporté"),
    135: ("Frappe multiple",                 "Dans un rayon de 2 cases, peut tirer des torpilles sur {1} cible(s). Récupération en 2 tours."),
    136: ("Forteresse d'acier",              "Récupère {1}% de PV en fin de tour"),
    137: ("Radar de conduite de tir",        "Ignore l'esquive, les fumigènes, l'état fantôme et l'EMCON"),
    138: ("Bombardement tactique",           "Dégâts infligés à la cible +{1}%"),
    139: ("Suppression aérienne",            "En bombardant une cible, ignore {1}% de sa défense"),
    141: ("Garde d'acier",                   "Dégâts subis des unités aériennes et aéroglisseurs -{2}% ; dégâts subis en terrain désertique -{1}%"),
    142: ("Suppression à longue portée",     "Dégâts -{1}% contre les ennemis à 1 case ; dégâts +{2}% contre les chars, artillerie ou aéroglisseurs à 2 cases ou plus"),
    143: ("Verrouillage visuel",             "En attaque comme en riposte, ignore l'esquive et les fumigènes"),
    144: ("Mitrailleuse lourde",             "Dégâts à l'infanterie +{1}%"),
    145: ("Déploiement de drones",           "Déploie un drone dans 1 case ; le drone agit indépendamment, n'attaque qu'une fois par tour, dure 1 tour. Récupération en 1 tour."),
    146: ("EMCON",                           "Récupère {1} PV et entre en état EMCON : ne peut être ciblé activement par les unités blindées, d'artillerie ou navales pendant 1 tour. L'EMCON prend fin à l'attaque. Récupération en 2 tours."),
    149: ("Calibration dynamique",           "Après avoir éliminé {1} unité(s) ce tour, portée +{2} pendant 1 tour"),
    150: ("Sabot perforant",                 "Sur un coup critique, {0}% de chances d'infliger +{1}% de dégâts supplémentaires"),
    151: ("Assaut tactique",                 "Entre en état Assaut : dégâts +{1}% ce tour et ignore les effets du terrain sur la mobilité. Durée 1 tour. Récupération en 3 tours."),
    152: ("Vectorisation de poussée",        "{1}% de chances d'esquiver les dégâts des unités terrestres ou navales, {2}% pour les frappes aériennes (hors missiles et bombes nucléaires)"),
    153: ("Contre-mesures aériennes",        "Dégâts +{1}% contre les hélicoptères. Après déplacement, mobilité du tour suivant -{2} (minimum 2 cases). Mobilité restaurée après un tour de repos à 1 case d'une ville ou d'une unité du génie alliée."),
    154: ("Attaque en chaîne",               "Dégâts aux blindés et artillerie +{0}%. Si la cible survit, elle reçoit l'effet Entrave pendant 1 tour. Si elle est anéantie, nouvelle attaque immédiate avec dégâts -{1}% chaque fois, jusqu'à {2} fois par tour."),
    155: ("Verrouillage BVR",                "Dégâts aux unités blindées, d'artillerie et navales +{2}%"),
    156: ("Missile à sous-munitions",        "Ce tour, en touchant une cible, inflige aussi {2}% de dégâts à {1} unité(s) dans 1 case (cibles non-infanterie en priorité). Durée 1 tour. Récupération en 3 tours."),
    157: ("Offensive implacable",            "Après une attaque, une attaque supplémentaire. Peut se déclencher {1} fois."),
}
